# Generated by Django 4.2.9 on 2024-11-29 23:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='created',
            field=models.DateTimeField(default=datetime.date.today, verbose_name='Date Created'),
        ),
        migrations.AddField(
            model_name='project',
            name='last_updated',
            field=models.DateTimeField(default=datetime.date.today, verbose_name='Date Last Updated'),
        ),
        migrations.AddField(
            model_name='project',
            name='tasks_done',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='total_tasks',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateTimeField(default=datetime.date.today, verbose_name='Date Started'),
        ),
    ]
