# Generated by Django 4.2.9 on 2024-11-30 02:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_tasks_done_project_jobs_done_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aim', models.CharField(max_length=500)),
                ('text_before', models.CharField(max_length=500)),
                ('text_after', models.CharField(max_length=500)),
                ('created', models.DateTimeField(default=datetime.date.today, verbose_name='Date Created')),
                ('updated', models.DateTimeField(default=datetime.date.today, verbose_name='Date Updated')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.project')),
            ],
        ),
    ]
