# Generated by Django 4.2.9 on 2024-11-30 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_jobs_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='created',
            field=models.DateTimeField(verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='job',
            name='updated',
            field=models.DateTimeField(verbose_name='Date Updated'),
        ),
    ]
