# Generated by Django 4.2.9 on 2024-11-30 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_job_created_alter_job_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='text_after',
            field=models.CharField(default='-------', max_length=500),
        ),
    ]
