# Generated by Django 4.2.9 on 2024-11-30 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_job_text_after'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='in_use',
            field=models.BooleanField(default=False),
        ),
    ]
